url: "https://expressjs.com"
baseurl: "/"

repository: expressjs/expressjs.com

# Site settings

defaults:
  -
    scope:
      path: "_posts" 
      type: "posts"
    values:
      layout: "post"
      menu: blog
      lang: en
  -
    scope:
      path: "en"
    values:
      lang: en
  - 
    scope:
      path: "index.md"
    values:
      lang: en
  -
    scope:
      path: "de"
    values:
      lang: de
  -
    scope:
      path: "es"
    values:
      lang: es
  -
    scope:
      path: "fr"
    values:
      lang: fr
  -
    scope:
      path: "it"
    values:
      lang: it
  -
    scope:
      path: "ja"
    values:
      lang: ja
  -
    scope:
      path: "ko"
    values:
      lang: ko
  -
    scope:
      path: "pt-br"
    values: 
      lang: "pt-br"  
  -
    scope:
      path: "zh-cn"
    values: 
      lang: "zh-cn"
  -
    scope:
      path: "zh-tw"
    values:
      lang: "zh-tw"

announcement: true # Enable or disable the announcements.

# Build settings

plugins:
  - jekyll-redirect-from
  - jekyll-github-metadata

highlighter: rouge
# library used for syntax highlighting

markdown: kramdown
kramdown:
 math_engine: mathjax
 input: GFM
 hard_wrap: false
 syntax_highlighter: rouge

exclude: 
  - [uk/CHANGELOG.md]
  - vendor/bundle
  - node_modules/
