name: PR Links

on:
  pull_request:
    branches: [redesign]
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Build site
        uses: withastro/action@15aa0a5a1e067940253e3b259413ab2ae882a740 # v5.2.0

      - name: Check links
        uses: lycheeverse/lychee-action@a8c4c7cb88f0c7386610c35eb25108e448569cb0 # v2.7.0
        with:
          args: |
            --root-dir $PWD/dist
            dist/
          fail: true
