name: Deploy Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'deploy-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Build and upload pages artifact
        uses: withastro/action@3eafd002e65cc31b4f0eae0bb05450d521562247 # v6
        with:
          path: .
          package-manager: npm
          out-dir: dist
        env:
          PUBLIC_ORAMA_PROJECT_ID: ${{ secrets.PUBLIC_ORAMA_PRODUCTION_PROJECT_ID }}
          PUBLIC_ORAMA_API_KEY: ${{ secrets.PUBLIC_ORAMA_PRODUCTION_API_KEY }}

  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
