name: Deploy Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'deploy-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build and upload pages artifact
        uses: withastro/action@v6
        with:
          path: .
          package-manager: npm
          out-dir: dist

  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-slim
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
